### ISSUE TITLE
Difference between service/repository in your code (reply expected)

### ISSUE THREAD

**Issue by ondrej-smola** [Tmthetom/ppj_project#5]

**Comment by Tmthetom** [comment]
Please provide more informations. Only thing i found is this difference in every pair of classes:
findByImage -> CommentRepository
getByImage -> CommentService
...
But this is based on Example: Lecture8_SpringDataJPAWithSpringBoot

**Comment by ondrej-smola** [comment]
Another way: Is AService needed when i have ARepository ? When i need to add some functionality, for example listing most upvoted or downvoted comments, should this functionality be implemented in CommentService or CommentRepository?

**Comment by Tmthetom** [comment]
When i have Repository, i dont need Service, because Repository implements all functionality. To answer your second question, functionality will be implemented in CommentRepository.

But Service layer gives you additional level of abstraction over data access from Repository. Service is kind of API and should transform input or output data somehow, call Repository and return expected result. To answer your first question, i will give you some example. My Repositories not always accepts objects, sometimes they need only ID, or some column from object. Thanks to my Services, i can always call service.method and pass object. When ID, or some column is required, i will extract from object in Service, so i dont need to call like repository.method1(object), repository.method2(object.column2), repository.method3(object), but i can call service.method1(object), service.method2(object), service.method3(object). Also when return value need to be changed, i can also do it in Service.

**Comment by ondrej-smola** [comment]
OK, so your services act as facade/adapter for repository.
